version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
  api:
    image: htcicek/ready-set-jet:api
    command: bash -c "rm -f tmp/pids/server.pid && while !</dev/tcp/db/5432; do sleep 1; done; rails db:create && rails db:migrate && rails db:seed && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - 3001:3001
    depends_on:
      - db
  web:
    image: htcicek/ready-set-jet:web
    ports:
      - 3000:3000
    depends_on:
      - api
